<?php
// $Id$

/**
 * @file
 * Contains necessary hook implementations, callbacks & helpers.
 */

/**
 * Implements hook_perm().
 */
function mailchimp_sender_perm() {
  return array('administer mailchimp sender');
}

/**
 * Implements hook_menu().
 */
function mailchimp_sender_menu() {
  $items = array();
  // list of users form mailchimp sevice.
  $items['admin/build/mailchimp_sender'] = array(
    'title' => 'Mailchimp sender',
    'description' => 'list of mailchimp users',
    'page callback' => '_my_test_func',
//    'page arguments' => array('mailchimp_sender_form_list'),
    'access arguments' => array('administer mailchimp sender'),
    'file' => 'MCAPI.class.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );

  return $items;
}

function _my_test_func() {
  //API Key - see http://admin.mailchimp.com/account/api
  $apikey = 'f26fed3956736322a5bfb4db96558441-us2';

  // A List Id to run examples against. use lists() to view all
  // Also, login to MC account, go to List, then List Tools, and look for the List ID entry
  $listId = 'YOUR MAILCHIMP LIST ID - see lists() method';

  // A Campaign Id to run examples against. use campaigns() to view all
  $campaignId = 'YOUR MAILCHIMP CAMPAIGN ID - see campaigns() method';

  //some email addresses used in the examples:
  $my_email = 'INVALID@example.org';
  $boss_man_email = 'INVALID@example.com';

  //just used in xml-rpc examples

  $api = new MCAPI($apikey);

  $retval = $api->campaignSendNow('813b3dea0c');

  if ($api->errorCode){
	  echo "Unable to Send Campaign!";
	  echo "\n\tCode=".$api->errorCode;
	  echo "\n\tMsg=".$api->errorMessage."\n";
  } else {
	  echo "Campaign Sent!\n";
  }

}

function mailchimp_sender_form_list($form_state, $ic = NULL) {
  $form['mailchimp_sender_site_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Website name'),
    '#description' => t('Name of the external website you wish to check.'),
    '#default_value' => isset($ic->site_name) ? $ic->site_name : '',
    '#required' => TRUE,
  );
  return $form;
}

